---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->


# asis_chunk

Insert code chunk into R Markdown documents.  An RStudio addin.

Inserts:  

> 
> ´´´{asis}
> 
> ´´´
> 

By Enrico Manlapig
emanlapig@westmont.edu


Main functions:   

* asis_chunk  

## Installation  
Development version:  

> install.packages("devtools")
>
> devtools::install_github("EnricoManlapig/asischunk")  

## Use

* Install package
* Add key command (e.g. mac: cmd-alt-shift-p, win: ctrl-alt-shift-p) by going to:   
    - *Tools* > *Addins* > *Browse Addins* > *Keyboard Shortcuts*.  
    - Find **asis code chunk** and select the field under *Shortcut*. 
    - Press desired key command.
    - Press *Apply*.
    - Press *Execute*.
* Press chosen key command inside an R Markdown document

The `asis` engine allows users to write markdown within chunks.  These chunks can then be conditionally rendered using parameters defined in the YAML or elsewhere in the document.


## Example

````
```{r}`r''`
solutions <- TRUE
```

What is half of $4x$?

```{asis student_prompt, include = !solutions}`r''`
Write your answer here: 
```

```{asis instructor_solutions, include = solutions}`r''`
Correct answer: $\frac{4x}{2}= 2x$
```

````

If the object `solutions` takes the value `FALSE`, then the first chunk, `student_prompt`, is rendered. If `solutions` takes the value `TRUE`, then the second chunk, `instructor_solutions`, is rendered. 

